import fs from 'node:fs';
import {scenario,Encounter,FAMILIES,rng} from '../simulator/core.mjs';
const out=process.argv.includes('--input')?process.argv[process.argv.indexOf('--input')+1]:null;
let samples=[];
if(out){const [header,...lines]=fs.readFileSync(out,'utf8').trim().split(/\r?\n/);const keys=header.split(',');samples=lines.map(line=>Object.fromEntries(line.split(',').map((v,i)=>[keys[i],v])));for(const s of samples){for(const k of ['brake','visibility','latency'])s[k]=Number(s[k]);if(!FAMILIES.includes(s.family)||!['measured','synthetic'].includes(s.origin)||!s.source_id||!['brake','visibility','latency'].every(k=>Number.isFinite(s[k])&&s[k]>0))throw Error('Invalid sample row; see data/README.md');}}
else{const r=rng(2027);for(const family of FAMILIES)for(let i=0;i<8;i++){const dust=family==='dust'||family==='combined',wet=family==='wet'||family==='combined';samples.push({sample_id:`S-${family}-${i}`,family,brake:wet?1.95+r()*.35:2.95+r()*.35,visibility:dust?42+r()*20:90+r()*20,latency:dust?.8+r()*.6:.2+r()*.3,origin:'synthetic',source_id:'built-in-2027'});}}
const keys=['sample_id','family','brake','visibility','latency','origin','source_id'];fs.writeFileSync('data/calibration-samples.csv',[keys.join(','),...samples.map(r=>keys.map(k=>r[k]).join(','))].join('\n')+'\n');
const bounds={},trainedCaps={},training=[],validation=[];
for(const family of FAMILIES){const a=samples.filter(r=>r.family===family);if(!a.length)throw Error(`Missing family: ${family}`);bounds[family]={brakeMin:Math.min(...a.map(r=>r.brake)),visibilityMin:Math.min(...a.map(r=>r.visibility)),latencyMax:Math.max(...a.map(r=>r.latency)),n:a.length,origin:[...new Set(a.map(r=>r.origin))]};
 for(const cap of [4,5,6,8,10,12]){let failures=0;for(let i=0;i<250;i++)failures+=Number(new Encounter({...scenario(61000+i,family),speedCap:cap,initialSpeed:cap,horizon:90},'guarded').run().bufferViolation);training.push({family,cap,n:250,failures});if(failures===0)trainedCaps[family]=cap;}
 if(!trainedCaps[family])throw Error('No feasible speed cap; the relevant family must be held.');
 let fittedFailures=0,selectedFailures=0;
 for(let i=0;i<1000;i++){const s=scenario(41000+i,family),b=bounds[family],decel=Math.max(.2,b.brakeMin-9.81*s.grade),delay=b.latencyMax+2*s.dt,cap=Math.min(12,decel*(Math.sqrt(delay*delay+2*(b.visibilityMin-8)/decel)-delay));fittedFailures+=Number(new Encounter({...s,initialSpeed:cap,speedCap:cap,horizon:90},'guarded').run().bufferViolation);
 selectedFailures+=Number(new Encounter({...s,initialSpeed:trainedCaps[family],speedCap:trainedCaps[family],horizon:90},'guarded').run().bufferViolation);}
 validation.push({family,n:1000,seedStart:41000,fittedFailures,selectedFailures,selectedCap:trainedCaps[family]});
}
fs.writeFileSync('config/policy.mjs','// Generated by scripts/calibrate.mjs. Caps in m/s.\nexport const TRAINED_CAPS='+JSON.stringify(trainedCaps)+';\n');
fs.writeFileSync('results/calibration.json',JSON.stringify({sourceKind:out?'imported':'synthetic',samples,bounds,training,trainedCaps,validation,method:'Largest candidate speed cap with zero observed clearance violations on 250 stress-test seeds per family; deployed with additional analytical envelope.',physicalValidation:false},null,2)+'\n');
console.log({trainedCaps,validation});
