"""Generate every numerical manuscript asset directly from experiment outputs."""
import os
os.environ.setdefault('MPLCONFIGDIR','/tmp/sieve-mpl')
import json
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
from matplotlib import font_manager
for p in Path('/System/Library/Fonts/Supplemental').glob('Times New Roman*.ttf'):
    font_manager.fontManager.addfont(str(p))
import matplotlib.pyplot as plt
import numpy as np
root=Path(__file__).resolve().parents[1]
result=json.loads((root/'results/summary.json').read_text()); disc=json.loads((root/'results/discovery.json').read_text())
plt.rcParams.update({'font.family':'Times New Roman','font.size':11,'axes.labelsize':12,'xtick.labelsize':11,'ytick.labelsize':11,'legend.fontsize':10,'axes.linewidth':0.8,'axes.spines.top':False,'axes.spines.right':False,'pdf.fonttype':42,'ps.fonttype':42,'savefig.bbox':'tight'})
colors=['#a65447','#397d80','#b29454','#627d98']
families=['nominal','dust','wet','combined']; policies=['baseline','guarded','no-speed-cap','no-brake-bound']
def cell(f,p,layer='extended-model'):return next(r for r in result['summary'] if r['family']==f and r['policy']==p and r['layer']==layer)
fig,ax=plt.subplots(figsize=(7.0,2.8));x=np.arange(4);width=.18
for i,p in enumerate(policies):
 rr=[cell(f,p) for f in families]; y=np.array([r['violations']/10 for r in rr]);ci=np.array([r['violationCI'] for r in rr])*100
 ax.bar(x+(i-1.5)*width,y,width,color=colors[i],edgecolor='white',linewidth=.45,hatch=['','///','..','xx'][i],label=['Baseline','Guarded','No speed cap','No brake bound'][i],zorder=3)
 ax.errorbar(x+(i-1.5)*width,y,yerr=np.maximum(0,np.array([y-ci[:,0],ci[:,1]-y])),fmt='none',ecolor='#253833',elinewidth=.85,capsize=2.5,zorder=4)
ax.set_xticks(x,[f.capitalize() for f in families]);ax.set_ylim(0,112);ax.set_ylabel('5 m requirement violations (%)');ax.grid(axis='y',alpha=.18,zorder=0);ax.legend(ncol=4,loc='upper center',bbox_to_anchor=(.5,1.19),frameon=False,fontsize=11,columnspacing=1.1,handlelength=1.3)
fig.savefig(root/'figures/violations.pdf');fig.savefig(root/'figures/violations.png',dpi=300);plt.close(fig)
fig,axes=plt.subplots(1,2,figsize=(7.0,3.1),gridspec_kw={'width_ratios':[1.4,1]})
for i,(s,label)in enumerate([('staged-guided','Staged, guided'),('staged-unguided','Staged, unguided'),('field-heavy','Field-heavy'),('sim-heavy','Sim-heavy'),('sim-only','Sim-only')]):
 axes[0].plot([r['budget'] for r in disc['curves']],[r[s] for r in disc['curves']],label=label,color=['#397d80','#b29454','#a65447','#627d98','#555'][i],lw=1.7,marker=['o','s','^','D','x'][i],markersize=3.5,ls=['-','--','-.',':','--'][i])
axes[0].axhline(10,color='#777',lw=.5);axes[0].set_xscale('log');axes[0].set_xlabel('Assumed test budget (units)');axes[0].set_ylabel('Expected modes discovered');axes[0].set_ylim(0,12.4);axes[0].legend(frameon=False,fontsize=9,loc='lower right',handlelength=2,labelspacing=.22);axes[0].grid(alpha=.15)
a=np.array([r['ratio'] for r in disc['sensitivity']]).reshape(3,3);im=axes[1].imshow(a,cmap='YlGnBu',vmin=0,vmax=25)
for i in range(3):
 for j in range(3):axes[1].text(j,i,f'{a[i,j]:.1f}×',ha='center',va='center',color='white' if a[i,j]>13 else '#17352f',fontsize=13)
axes[1].set_xticks(range(3),['0','0.5','1']);axes[1].set_yticks(range(3),['1','4','12']);axes[1].set_xlabel('Physical targeting gain');axes[1].set_ylabel('Simulation gain');fig.tight_layout();fig.savefig(root/'figures/discovery.pdf');fig.savefig(root/'figures/discovery.png',dpi=300);plt.close(fig)
# Numeric macros and complete table rows are generated, never transcribed.
macros={'TotalRuns':f"{result['metadata']['totalRuns']:,}",'NominalViolations':str(cell('nominal','baseline')['violations']),'DustViolations':str(cell('dust','baseline')['violations']),'WetViolations':str(cell('wet','baseline')['violations']),'CombinedViolations':str(cell('combined','baseline')['violations']),'GuardedCombined':str(cell('combined','guarded')['violations']),'GuardedCollisions':str(cell('combined','guarded')['collisions']),'FieldCost':f"{disc['thresholds']['field-heavy']:,}",'GuidedCost':f"{disc['thresholds']['staged-guided']:,}",'UnguidedCost':f"{disc['thresholds']['staged-unguided']:,}",'CostRatio':f"{disc['thresholds']['field-heavy']/disc['thresholds']['staged-guided']:.2f}",'NoGainRatio':f"{disc['thresholds']['field-heavy']/disc['thresholds']['staged-unguided']:.2f}"}
(root/'results/numbers.tex').write_text('% Generated by scripts/figures.py\n'+''.join('\\newcommand{\\'+k+'}{'+v+'}\n' for k,v in macros.items()))
lines=[]
for f in families:
 a,b=cell(f,'baseline'),cell(f,'guarded');lo,hi=b['violationCI'];lines.append(f"{f.capitalize()} & {a['violations']} & {b['violations']} & {100*lo:.2f}--{100*hi:.2f} & {a['collisions']} / {b['collisions']} \\\\")
(root/'results/safety-table.tex').write_text('\n'.join(lines)+'\n')
# Representative paired trajectory, same seed as screenshots.
rep=json.loads((root/'results/replays.json').read_text());fig,axes=plt.subplots(1,2,figsize=(7.0,2.8))
for i,p in enumerate(['baseline','guarded']):
 r=rep[f'combined/{p}/extended-model'];t=[q['t'] for q in r['trace']];axes[0].plot(t,[q['gap'] for q in r['trace']],color=colors[i],label=p.capitalize());axes[1].plot(t,[q['v'] for q in r['trace']],color=colors[i])
axes[0].axhline(5,color='#666',ls='--',lw=.7);axes[0].set_ylabel('Bumper clearance (m)');axes[1].set_ylabel('Speed (m/s)');axes[0].legend(frameon=False);[a.set_xlabel('Time (s)') for a in axes];[a.grid(alpha=.15) for a in axes];fig.tight_layout();fig.savefig(root/'figures/trajectory.pdf');plt.close(fig)
