import {chromium} from 'playwright';
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1.5});const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('crash',()=>errors.push('Browser page crashed'));const diagnostics=[];
const shots=[['simulator-overview','family=combined&policy=guarded&view=overview&t=9',false],['mine-overview','family=combined&policy=guarded&view=overview&t=9',true],['mine-guarded','family=combined&policy=guarded&view=follow&t=35',true],['mine-baseline','family=combined&policy=baseline&view=follow&t=35',true],['mine-driver','family=combined&policy=guarded&view=driver&t=18',true],['mine-left','family=nominal&policy=guarded&view=left&t=8',true],['mine-right','family=nominal&policy=guarded&view=right&t=8',true],['mine-extreme-dust','family=extreme-dust&policy=integrated&view=driver&t=35',true],['mine-landslide','family=landslide&policy=integrated&view=follow&t=35',true],['mine-field-crew','family=human-crossing&policy=integrated&view=field&t=35',true],['mine-nominal','family=nominal&policy=integrated&view=overview&t=7',true]];
for(const view of ['loading','unloading','operations','passing'])shots.push([`mine-${view}`,`family=nominal&policy=integrated&view=${view}&t=12`,true]);
const only=process.argv[2],previous=only?JSON.parse(fs.readFileSync('results/screenshots.json')):null;
const manifest=[];
for(const[name,params,paper]of shots.filter(s=>!only||s[0]===only)){await page.goto(`http://127.0.0.1:8766/simulator/?paused&${paper?'paper&':''}${params}`);await page.waitForFunction(()=>window.sieve?.ready);await page.waitForTimeout(1200);await page.screenshot({path:`figures/${name}.png`});diagnostics.push(await page.evaluate(()=>window.sieve.stats));manifest.push({file:`figures/${name}.png`,query:params,paper,result:await page.evaluate(()=>{const {trace,...r}=window.sieve.result;return r;})});}
// Exercise controls and export, checking browser/core agreement.
await page.goto('http://127.0.0.1:8766/simulator/?paused');await page.waitForFunction(()=>window.sieve?.ready);await page.selectOption('#policy','baseline');await page.click('#restart');await page.evaluate(()=>window.sieve.setTime(35));if(await page.locator('#status').innerText()!=='COLLISION')throw Error('Baseline replay failed');
const downloadPromise=page.waitForEvent('download');await page.click('#export');const download=await downloadPromise;await download.saveAs('results/browser-evidence.json');
for(const view of ['driver','left','right','follow','overview','top','field','loading','unloading','operations','passing']){await page.click(`[data-view="${view}"]`);await page.waitForTimeout(250);}
await page.click('[data-view="top"]');await page.click('#shift');await page.waitForSelector('#shiftCards article');if(await page.locator('#shiftCards article').count()!==4)throw Error('Shift dashboard failed');await page.click('#closeShift');await page.click('#overlay');if(await page.locator('#overlay').getAttribute('aria-pressed')!=='false')throw Error('Overlay toggle failed');
if(previous){for(let i=0;i<previous.manifest.length;i++){if(!manifest.some(x=>x.file===previous.manifest[i].file)){manifest.push(previous.manifest[i]);diagnostics.push(previous.renderDiagnostics[i]);}}errors.push(...previous.browserErrors);}
fs.writeFileSync('results/screenshots.json',JSON.stringify({viewport:{width:1600,height:1000,scale:1.5},manifest,browserErrors:errors,renderDiagnostics:diagnostics},null,2));
await browser.close();const {execFileSync}=await import('node:child_process');execFileSync('python3',['scripts/image_formats.py']);if(errors.length)throw Error(errors.join('\n'));console.log(`${only||'Fifteen screenshots'} and interaction/export checks passed.`);
